# first attempt at an environment.yaml file for the omds project so that
# conda can recreate the environment systematically
#
# call with
# conda env create -f environment.yaml
#
# remove with
# conda remove --name omds --all
#
# Hint: make sure all keys use spaces not tabs. Check for \t if there is a conda error.
---
name: omds
dependencies:
    - python=3.11
    - numpy
    - scipy
    - jupyter
    - pyyaml
    - conda-forge::rdflib
    - conda-forge::h5py
    - pip
    - pip:
        - scidata
        - scidatalib
        - globus-sdk
